apiVersion: v1
kind: Service
metadata:
  name: quiz-management-service
spec:
  selector:
    app: quiz-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort    
