apiVersion: v1
kind: Service
metadata:
  name: quiz-management-service
spec:
  selector:
    app: quiz-management
  ports:
    - name: rest 
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30502
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
      nodePort: 30552
  type: NodePort    
