apiVersion: v1
kind: Service
metadata:
  name: quiz-management-service
spec:
  selector:
    app: quiz-management
  ports:
    - name: rest 
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30501
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30551
  type: NodePort    
